### ISSUE TITLE
Peer to peer review 

### ISSUE THREAD

**Issue by isume295** [lordksix/Minimalistic-ToDoList-App#7]
You did a great job so far! just a few suggestions to be addressed

- We suggest you use a switch case instead of else if conditions to make your code shorter
- We kindly suggest you use a camel case for all your variables to make it more understandable

**Comment by lordksix** [comment]
Thank you for the feedback. Changes applied in commit 6b7095de58e4242e5d04c0f54389d16be2b8b033
